# Generated by Django 3.2.5 on 2021-08-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=8)),
                ('orgaoEmissor', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('nacionalidade', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('dataNascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Nenhuma das opções')], max_length=1)),
                ('escolaridade', models.CharField(max_length=255)),
                ('email', models.EmailField(default='Nulo', max_length=255)),
            ],
        ),
    ]
