# Generated by Django 3.2.5 on 2021-08-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiFuncionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfuncionarios',
            name='email',
            field=models.EmailField(default='Nulo', max_length=255),
        ),
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='cep',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='cpf',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='dataNascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='rg',
            field=models.CharField(max_length=8),
        ),
    ]
