# Generated by Django 3.2.5 on 2021-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiFuncionarios', '0002_auto_20210808_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='cpf',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='rg',
            field=models.IntegerField(max_length=8),
        ),
    ]
