# Generated by Django 3.2.5 on 2021-08-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiFuncionarios', '0003_auto_20210808_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfuncionarios',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Nenhuma das opções')], max_length=1),
        ),
    ]
